name: Golang

on:
  push:
    branches:
      - master
    paths-ignore:
      - CHANGELOG.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - CHANGELOG.md

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        go:
          - '1.20'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: make bin
